import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import '@/app/globals.css'
import I18nTranslationsProvider from '@/providers/I18nTranslationsProvider'
import { initTranslations } from '@/utils/i18n'
import Providers from '@/providers/Providers'
import { cn } from '@/utils'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin']
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin']
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

const i18nNamespaces = ['common']

export default async function RootLayout({
  children,
  params
}: {
  children: React.ReactNode
  params: { locale: string }
}) {
  const { locale } = await params
  const { resources } = await initTranslations(locale, i18nNamespaces)

  return (
    <html lang={locale}>
      <body className={cn(geistSans.variable, geistMono.variable, 'antialiased')}>
        <I18nTranslationsProvider
          locale={locale}
          namespaces={i18nNamespaces}
          resources={resources}
        >
          <Providers>{children}</Providers>
        </I18nTranslationsProvider>
      </body>
    </html>
  )
}
