import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import '@/app/globals.css'
import Providers from '@/providers/Providers'
import { cn } from '@/utils'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
  params,
}: {
  children: React.ReactNode
  params: { locale: string }
}) {
  const { locale } = await params

  return (
    <html lang={locale}>
      <body
        className={cn(geistSans.variable, geistMono.variable, 'antialiased')}
      >
        <Providers>{children}</Providers>
      </body>
    </html>
  )
}
